/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.housing;

import controller.HousingCtrl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class HousingUpdate extends javax.swing.JPanel {
    private HousingCtrl controller = new HousingCtrl();
    /**
     * Creates new form HousingUpdate
     */
    public HousingUpdate() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        housingUpdate = new javax.swing.JPanel();
        house = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        housingType = new javax.swing.JComboBox<>();
        category = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        housingList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        housingTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 512));

        jLabel1.setText("Establecimiento");

        housingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "Hostal", "Apartamento" }));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Establecimiento");

        jLabel3.setText("Categoria");

        jLabel4.setText("Id");

        javax.swing.GroupLayout housingUpdateLayout = new javax.swing.GroupLayout(housingUpdate);
        housingUpdate.setLayout(housingUpdateLayout);
        housingUpdateLayout.setHorizontalGroup(
            housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(housingUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(housingUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(housingType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(housingUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(housingUpdateLayout.createSequentialGroup()
                        .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(id))))
                .addGap(152, 152, 152))
            .addGroup(housingUpdateLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        housingUpdateLayout.setVerticalGroup(
            housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(housingUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, housingUpdateLayout.createSequentialGroup()
                        .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(house, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(housingUpdateLayout.createSequentialGroup()
                                .addComponent(housingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(housingUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(50, 50, 50))
                            .addGroup(housingUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(106, 106, 106))))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        housingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Establecimiento", "Direccion", "Tipo de establecimiento", "Categoria"
            }
        ));
        housingTable.setRowSelectionAllowed(false);
        housingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                housingTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                housingTableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(housingTable);

        javax.swing.GroupLayout housingListLayout = new javax.swing.GroupLayout(housingList);
        housingList.setLayout(housingListLayout);
        housingListLayout.setHorizontalGroup(
            housingListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        housingListLayout.setVerticalGroup(
            housingListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(housingList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(housingUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(housingUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(housingList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String housingHouse = house.getText();
        String houseType = housingType.getSelectedItem().toString();
        int housingCategory = Integer.parseInt(category.getSelectedItem().toString());
        
        if(id.getText().matches("^[0-9]")){
            int housingId = Integer.parseInt(id.getText());
            int result = JOptionPane.showConfirmDialog(null, "¿Está seguro que quiere actualizar el campo?", "", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
             
            if(result == 0) controller.update(housingId, housingHouse, houseType, housingCategory);
        }
        else JOptionPane.showMessageDialog(null, "El id no puede tiene que ser un número");
        
        showTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void housingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_housingTableMouseClicked
          int row = housingTable.getSelectedRow();
          
          id.setText(String.valueOf(housingTable.getValueAt(row, 0)));
          house.setText(String.valueOf(housingTable.getValueAt(row, 1)));
          String house = String.valueOf(housingTable.getValueAt(row, 3));
          switch(house){
              case "Hotel": housingType.setSelectedIndex(0);
              break;
              case "Hostal": housingType.setSelectedIndex(1);
              break;
              case "Apartamento": housingType.setSelectedIndex(2);
              break;
          }

        category.setSelectedIndex(Integer.parseInt(String.valueOf(housingTable.getValueAt(row, 4))) - 1);
          
    }//GEN-LAST:event_housingTableMouseClicked

    private void housingTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_housingTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_housingTableMouseEntered

    public void showTable(){
        DefaultTableModel modelTable = (DefaultTableModel) housingTable.getModel();
        
        modelTable.setRowCount(0);
        
        for(Object[] i : controller.read()){
           modelTable.addRow(i);
        }
        
        housingTable.setModel(modelTable);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField house;
    private javax.swing.JPanel housingList;
    private javax.swing.JTable housingTable;
    private javax.swing.JComboBox<String> housingType;
    private javax.swing.JPanel housingUpdate;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
